FROM node:16.14.0
WORKDIR /wise-old-man/discord-bot

ENV NODE_ENV=development

# Install cairo dependencies (for rendering canvas images)
RUN apt-get update && apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm i

# Copy the rest of the files into the container
COPY . .

# Transpile the TypeScript code into JavaScript
RUN npm run build

