FROM node:16.14.0
WORKDIR /wise-old-man/discord-bot

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm i
RUN npm i pm2 -g

# Copy the rest of the files into the container
COPY . .

# Generate the prisma client
RUN npx prisma generate

# Transpile the TypeScript code into JavaScript
RUN npm run build

CMD ["npm", "run", "prod"]
